//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationRetrievalManager.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InformationRetrievalManager.Core.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} allows maximal count {1}..
        /// </summary>
        internal static string ValidateCollectionAttribute_MaxCountLimitMessage {
            get {
                return ResourceManager.GetString("ValidateCollectionAttribute_MaxCountLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not fit the format..
        /// </summary>
        internal static string ValidateStringAttribute_CanContainRegexLimitMessage {
            get {
                return ResourceManager.GetString("ValidateStringAttribute_CanContainRegexLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string ValidateStringAttribute_IsRequiredLimitMessage {
            get {
                return ResourceManager.GetString("ValidateStringAttribute_IsRequiredLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exceeded the maximal allowed length of {1} characters..
        /// </summary>
        internal static string ValidateStringAttribute_MaxLengthLimitMessage {
            get {
                return ResourceManager.GetString("ValidateStringAttribute_MaxLengthLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exceeded the minimal allowed length of {1} characters..
        /// </summary>
        internal static string ValidateStringAttribute_MinLengthLimitMessage {
            get {
                return ResourceManager.GetString("ValidateStringAttribute_MinLengthLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not exist..
        /// </summary>
        internal static string ValidateStringAttribute_NullLimitMessage {
            get {
                return ResourceManager.GetString("ValidateStringAttribute_NullLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid JSON string..
        /// </summary>
        internal static string ValidateStringAttribute_ValidateJsonLimitMessage {
            get {
                return ResourceManager.GetString("ValidateStringAttribute_ValidateJsonLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} allows maximal value {1}..
        /// </summary>
        internal static string ValidateTimespanAttribute_MaxValueLimitMessage {
            get {
                return ResourceManager.GetString("ValidateTimespanAttribute_MaxValueLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} allows minimal value {1}..
        /// </summary>
        internal static string ValidateTimespanAttribute_MinValueLimitMessage {
            get {
                return ResourceManager.GetString("ValidateTimespanAttribute_MinValueLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not exist..
        /// </summary>
        internal static string ValidateTimespanAttribute_NullLimitMessage {
            get {
                return ResourceManager.GetString("ValidateTimespanAttribute_NullLimitMessage", resourceCulture);
            }
        }
    }
}
